server:
  port: 8080
  tomcat:
    # unlimited
    max-swallow-size: -1
    max-http-form-post-size: -1
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet
